package com.mkvbs.food_preferences_service.utils.ingredient

import jakarta.servlet.http.HttpServletRequest
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class LoggingHelper {

    companion object {

        /**
         * Logs an incoming HTTP request in a structured and consistent format.
         *
         * This method should be called at the entry point of a controller endpoint.
         * It records essential metadata describing the incoming request, including:
         *
         * - HTTP method (GET, POST, PUT, DELETE, ...)
         * - fully resolved endpoint path
         * - path variable values extracted from the request
         * - request body (if provided)
         * - client IP address
         * - authenticated user ID obtained from the `X-User-Id` header
         *
         * This log entry is helpful for tracing incoming traffic, debugging unexpected
         * client behavior, and correlating requests with their originating user
         * in distributed microservice environments.
         *
         * **Note:**
         * For requests containing sensitive or large bodies, consider logging the body
         * only conditionally (e.g., DEBUG level) or masking sensitive fields.
         *
         * @param controllerClass the controller class generating the log; used as the logger source
         * @param method the HTTP method of the incoming request (e.g., `"GET"`, `"POST"`)
         * @param path the full resolved path of the endpoint being called
         * @param pathVariables a map of path variable names and their resolved values
         * @param body optional request body representation to be logged (may be `null`)
         * @param request the {@link HttpServletRequest} providing client IP and header information
         */
        fun logRequest(
            controllerClass: Class<*>,
            method: String,
            path: String,
            pathVariables: Map<String, Any?> = emptyMap(),
            body: Any? = null,
            request: HttpServletRequest
        ) {
            val logger: Logger = LoggerFactory.getLogger(controllerClass)

            val clientIp = request.remoteAddr ?: "unknown"
            val loggedUserId = request.getHeader("X-User-Id") ?: "anonymous"

            val pathVarsString = pathVariables.ifEmpty { "{}" }
            val bodyString = body?.toString() ?: "none"

            logger.info(
                "Incoming request: method=$method, path=$path, pathVariables=$pathVarsString, " +
                        "body=$bodyString, clientIp=$clientIp, loggedUserId=$loggedUserId"
            )
        }

        /**
         * Logs an outgoing HTTP response in a standardized and structured format.
         *
         * This method should be called at the end of controller request handling to record
         * key response metadata such as the status code, execution time, path variables,
         * client information, and the authenticated user's identifier.
         *
         * The log entry generated by this method provides:
         * - HTTP status of the response
         * - the endpoint path that was executed
         * - values of path variables
         * - total request processing time in milliseconds
         * - client's IP address
         * - ID of the currently logged-in user (taken from the `X-User-Id` header)
         *
         * This log is useful for performance monitoring, troubleshooting failed requests,
         * and analysing request flow in distributed microservice systems.
         *
         * @param controllerClass the class of the controller generating the log; used to bind the logger
         * @param path the fully resolved HTTP endpoint path that produced the response
         * @param status HTTP response status code (e.g., 200, 400, 500)
         * @param durationMs total time in milliseconds it took to process the request
         * @param request the current {@link HttpServletRequest}, used to extract client IP and headers
         */
        fun logResponse(
            controllerClass: Class<*>,
            path: String,
            status: Int,
            durationMs: Long,
            request: HttpServletRequest
        ) {
            val logger: Logger = LoggerFactory.getLogger(controllerClass)

            val clientIp = request.remoteAddr ?: "unknown"
            val loggedUserId = request.getHeader("X-User-Id") ?: "anonymous"

            logger.info(
                "Outgoing response: status=$status, path=$path, " +
                        "durationMs=${durationMs}ms, clientIp=$clientIp, loggedUserId=$loggedUserId"
            )
        }

    }
}
